import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Slider from "@/components/Slider";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [imgState, setImgState] = useState();
  const imgObj = [
    {
      img: "https://images.squarespace-cdn.com/content/v1/5a2f39bba9db09ee7335b85a/1565301606403-55ZAEF5FN07C8AA039TI/07_S3K6333.jpg",
      alt: "part1",
    },
    {
      img: "https://images.squarespace-cdn.com/content/v1/5a2f39bba9db09ee7335b85a/1565301591657-5FFNAHHAJICJWKLAZ9HV/01_S3K6237.jpg",
      alt: "part2",
    },
    {
      img: "https://www.pakutaso.com/shared/img/thumb/shikun20220402_114719-2_TP_V.jpg",
      alt: "part3",
    },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles["main"]}>
        <section className={styles["menu"]}>
          <ul className={styles["menu-photo-list"]}>
            <li>
              <a>1</a>
            </li>
            <li>
              <a>2</a>
            </li>
            <li>
              <a>3</a>
            </li>
            <li>
              <a>4</a>
            </li>
            <li>
              <a>5</a>
            </li>
          </ul>
        </section>
        <section className={styles["slide"]}>
          <Slider
            imgObj={imgObj}
            imgState={imgState}
            setImgState={setImgState}
          />
        </section>
      </main>
    </>
  );
}
