import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Slider from "@/components/Slider";
import { useEffect, useState } from "react";
import { client } from "../libs/client";
import { css } from "@emotion/react";
import Link from "next/link";
import Menu from "@/components/menu";
import { useRouter } from "next/router";

export default function Home({ works }) {
  const router = useRouter();
  const [imgPreset, setImagePreset] = useState(works.photos[0].img);
  const [slideNum, setSlideNum] = useState(1);
  const [controler, setControler] = useState("1");
  console.log(works);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles["main"]}>
        <Menu
          works={works}
          imgPreset={imgPreset}
          setImagePreset={setImagePreset}
          slideNum={slideNum}
          setSlideNum={setSlideNum}
          controler={controler}
        ></Menu>
        <section>aaaaaaa</section>
      </main>
    </>
  );
}
export const getStaticProps = async () => {
  const data = await client
    .get({ endpoint: "works" })
    .then((res) => {
      return res;
    })
    .catch((err) => {
      console.log(err);
    });

  return {
    props: {
      works: data,
    },
  };
};
