name: upload-server-onPush
on:
  push:
    branches: [develop]
  repository_dispatch:
    types: [update-posts]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install NPM packages
        run: npm i
      - name: Build Next.js App
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SERVICE_DOMAIN: ${{ secrets.SERVICE_DOMAIN }}
        run: npm run build

      # - name: Export Next.js app
      #   run: npm run export

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /kd/
          protocol: ftps
